name: updatedb
on:
  push:
    branches: [ master ]
env:
  ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: pip install -r .github/requirements.txt
      - name: Update Pinecone database
        run: |
          python .github/update_db.py || true
          if [ $? -ne 0 ]; then
            echo "Failed to update Pinecone database" > /dev/stderr 
            exit 1
          fi

          # Add your custom notifications here
        env:
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
